# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{xxx}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jakub Kuźma", "Wojciech Wnętrzak"]
  s.date = %q{2010-02-05}
  s.default_executable = %q{xxx}
  s.description = %q{To watch a porn just type from your command line: xxx}
  s.email = %q{qoobaa@gmail.com}
  s.executables = ["xxx"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/xxx",
     "lib/xxx.rb",
     "lib/xxx/szukaj_cipki.rb",
     "lib/xxx/youporn.rb",
     "test/helper.rb",
     "test/test_xxx.rb",
     "xxx.gemspec"
  ]
  s.homepage = %q{http://github.com/qoobaa/xxx}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Porn of the day}
  s.test_files = [
    "test/helper.rb",
     "test/test_xxx.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<launchy>, [">= 0"])
      s.add_runtime_dependency(%q<mechanize>, [">= 0"])
    else
      s.add_dependency(%q<launchy>, [">= 0"])
      s.add_dependency(%q<mechanize>, [">= 0"])
    end
  else
    s.add_dependency(%q<launchy>, [">= 0"])
    s.add_dependency(%q<mechanize>, [">= 0"])
  end
end

